apiVersion: v1
kind: Service
metadata:
  name: project-2-service
spec:
  selector:
    app: project-2     # Must match pod label
  type: NodePort
  ports:
    - port: 9595      # Port inside cluster
      targetPort: 9595 # Container port
      nodePort: 30008  # Port exposed on each node

